module OperationAlgebra

using LinearAlgebra
using ..CoreTypes: FactorizationResult, EquivalenceClassOnly, InsufficientObservation

export ordinary_commutator,
       graded_commutator,
       algebra_closure_basis,
       commutant_basis,
       center_basis,
       factorization_diagnostic

ordinary_commutator(left::AbstractMatrix, right::AbstractMatrix) =
    left * right - right * left

"""Return the graded commutator for parity bits zero (even) or one (odd)."""
function graded_commutator(
    left::AbstractMatrix,
    right::AbstractMatrix,
    left_parity::Integer,
    right_parity::Integer,
)
    left_parity in (0, 1) || throw(ArgumentError("left parity must be zero or one"))
    right_parity in (0, 1) || throw(ArgumentError("right parity must be zero or one"))
    size(left, 2) == size(right, 1) && size(right, 2) == size(left, 1) ||
        throw(DimensionMismatch("graded commutator operands are incompatible"))
    sign = isodd(left_parity * right_parity) ? -1 : 1
    return left * right - sign * right * left
end

function _validate_generators(generators::AbstractVector{<:AbstractMatrix})
    isempty(generators) && throw(ArgumentError("at least one operation generator is required"))
    dimension = size(first(generators), 1)
    dimension == size(first(generators), 2) ||
        throw(DimensionMismatch("operation generators must be square"))
    for generator in generators
        size(generator) == (dimension, dimension) ||
            throw(DimensionMismatch("operation generators have inconsistent dimensions"))
        all(isfinite, generator) || throw(ArgumentError("operation generator is non-finite"))
    end
    return dimension
end

function _rank_tolerance(matrix::AbstractMatrix)
    scale = max(1.0, opnorm(ComplexF64.(matrix), Inf))
    return max(size(matrix)...) * eps(Float64) * scale * 32
end

function _try_add!(vectors::Vector{Vector{ComplexF64}}, candidate::AbstractMatrix, tolerance::Real)
    residual = vec(ComplexF64.(candidate))
    original_norm = norm(residual)
    original_norm == 0 && return false
    for basis_vector in vectors
        residual -= basis_vector * dot(basis_vector, residual)
    end
    residual_norm = norm(residual)
    residual_norm > tolerance * max(1.0, original_norm) || return false
    push!(vectors, residual / residual_norm)
    return true
end

"""
    algebra_closure_basis(generators)

Return a Hilbert--Schmidt-orthonormal basis for the finite-dimensional unital
star-algebra generated by the supplied matrices.
"""
function algebra_closure_basis(generators::AbstractVector{<:AbstractMatrix})
    dimension = _validate_generators(generators)
    tolerance = maximum(_rank_tolerance(generator) for generator in generators)
    vectors = Vector{Vector{ComplexF64}}()
    _try_add!(vectors, Matrix{ComplexF64}(I, dimension, dimension), tolerance)
    for generator in generators
        _try_add!(vectors, generator, tolerance)
        _try_add!(vectors, generator', tolerance)
    end

    changed = true
    while changed
        changed = false
        matrices = [reshape(vector, dimension, dimension) for vector in vectors]
        for left in matrices, right in matrices
            if _try_add!(vectors, left * right, tolerance)
                changed = true
                length(vectors) == dimension^2 && break
            end
        end
        length(vectors) == dimension^2 && break
    end
    return [reshape(vector, dimension, dimension) for vector in vectors]
end

function _commutant_constraint(generators::AbstractVector{<:AbstractMatrix})
    dimension = _validate_generators(generators)
    identity = Matrix{ComplexF64}(I, dimension, dimension)
    blocks = Matrix{ComplexF64}[]
    for generator in generators
        matrix = ComplexF64.(generator)
        push!(blocks, kron(transpose(matrix), identity) - kron(identity, matrix))
    end
    return reduce(vcat, blocks), dimension
end

"""Return an orthonormal vector-space basis of the simultaneous commutant."""
function commutant_basis(generators::AbstractVector{<:AbstractMatrix})
    constraint, dimension = _commutant_constraint(generators)
    tolerance = _rank_tolerance(constraint)
    kernel = nullspace(constraint; atol = tolerance, rtol = 0.0)
    return [reshape(kernel[:, column], dimension, dimension) for column in axes(kernel, 2)]
end

"""Return a basis for the center of the generated star-algebra."""
function center_basis(generators::AbstractVector{<:AbstractMatrix})
    algebra = algebra_closure_basis(generators)
    constraint, dimension = _commutant_constraint(generators)
    algebra_columns = hcat(vec.(algebra)...)
    restricted = constraint * algebra_columns
    tolerance = _rank_tolerance(restricted)
    coefficients = nullspace(restricted; atol = tolerance, rtol = 0.0)
    return [reshape(algebra_columns * coefficients[:, column], dimension, dimension)
            for column in axes(coefficients, 2)]
end

"""
Return algebra/commutant/center dimensions. A nontrivial center is reported as
insufficient for a unique global tensor-factor answer.
"""
function factorization_diagnostic(generators::AbstractVector{<:AbstractMatrix})
    dimension = _validate_generators(generators)
    algebra_dimension = length(algebra_closure_basis(generators))
    commutant_dimension = length(commutant_basis(generators))
    center_dimension = length(center_basis(generators))
    status = center_dimension == 1 ? EquivalenceClassOnly : InsufficientObservation
    return FactorizationResult(
        dimension,
        algebra_dimension,
        commutant_dimension,
        center_dimension,
        status,
    )
end

end
